branch-defaults:
  default:
    environment: knowitalllive2
    group_suffix: null
global:
  application_name: knowitalllive2
  branch: null
  default_ec2_keyname: knowItAllKeypair
  default_platform: python2.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
